apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 8081;
      listen [::]:8081;

      server_name _;

      root /app/site;

      location /api {
          try_files $uri @wsgi;
      }

      location /auth {
          try_files $uri @wsgi;
      }

      location @wsgi {
        proxy_pass http://bgmapi.default.svc.cluster.local:8080;
      }

      location / {
        try_files $uri /index.html;
      }

      location ~* .(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
          access_log off;
          log_not_found off;
          expires max;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgmnginx
spec:
  selector:
    matchLabels:
      run: bgmnginx
  replicas: 1
  template:
    metadata:
      labels:
        run: bgmnginx
    spec:
      containers:
      - name: bgmnginx
        image: localhost:32000/bgm-front
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf # mount nginx-conf volumn to /etc/nginx
          subPath: default.conf
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: default.conf
      - name: log
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgmapi
spec:
  selector:
    matchLabels:
      run: bgmapi
  replicas: 1
  template:
    metadata:
      labels:
        run: bgmapi
    spec:
      containers:
      - name: bgmapi
        image: localhost:32000/bgm-back
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_URL
            value: "postgres.default.svc.cluster.local"
          - name: POSTGRES_USER
            value: postgresadmin
          - name: POSTGRES_PASSWORD
            value: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: bgmnginx
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 32501
    protocol: TCP
    targetPort: 8081
  selector:
    run: bgmnginx

---
apiVersion: v1
kind: Service
metadata:
  name: bgmapi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: bgmapi


